### ISSUE TITLE
strip does not work with fg

### ISSUE THREAD

**Issue by kinow** [gvalkov/python-ansimarkup#16]
Hi,

The following test fails for me using `master` version

```python
def test_strip_01(am):
	assert am.strip('<b>Bold</b>') == 'Bold'
	assert am.strip('<red>Red</red>') == 'Red'
	assert am.strip('<fg #ff0000>Red</fg>') == 'Red'
```

The error output on my IDE is

```

test_markup.py .................F
tests/test_markup.py:249 (test_strip_01)
Red</fg> != Red

Expected :Red
Actual   :Red</fg>
<Click to see difference>

am = <ansimarkup.markup.AnsiMarkup object at 0x7fe652f67e10>

    def test_strip_01(am):
    	assert am.strip('<b>Bold</b>') == 'Bold'
    	assert am.strip('<red>Red</red>') == 'Red'
>   	assert am.strip('<fg #ff0000>Red</fg>') == 'Red'
E    AssertionError: assert 'Red</fg>' == 'Red'
E      - Red</fg>
E      + Red

test_markup.py:253: AssertionError
```

**Comment by Delgan** [comment]
Hi @kinow, I can't find `test_strip_01()` on `master`, is this a function you added by yourself?

I guess the output is expected based on how `ansimarkup` is currently implemented: closing tag only matches entry tag if the attributes like `#ff0000` are the same.
For `"<fg #ff0000>Red</fg>"` to return `"Red"` when stripped, the closing tag should be `"</fg #ff0000>"`, otherwise the `"</fg>"` is ignored as it does not have any corresponding entry tag.

**Comment by kinow** [comment]
Hi @Delgan 

>I can't find test_strip_01() on master, is this a function you added by yourself?

Yes, that was a local test I wrote. Sorry for not mentioning it.

>I guess the output is expected based on how ansimarkup is currently implemented: closing tag only matches entry tag if the attributes like #ff0000 are the same.

Oh, got it, so just need to remember to close it with the same markup attributes. And I just realized that the docs mention it too, after re-reading the documentation. 

Thanks!
Bruno
